services:
  - type: web
    name: traderpro
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DERIV_APP_ID
        value: "33stOEdBBT6OJNq5sdS5f"
      - key: OAUTH_REDIRECT_URL
        value: https://traderpro.onrender.com/redirect.html
